//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ACCESS_MENU> TB_ACCESS_MENU { get; set; }
        public virtual DbSet<TB_MENU> TB_MENU { get; set; }
        public virtual DbSet<TB_ROLE> TB_ROLE { get; set; }
        public virtual DbSet<TB_SUBMENU> TB_SUBMENU { get; set; }
        public virtual DbSet<TB_USER> TB_USER { get; set; }
        public virtual DbSet<JOB_PORTAL> JOB_PORTAL { get; set; }
        public virtual DbSet<TB_CLIENT> TB_CLIENT { get; set; }
        public virtual DbSet<TB_SKILL> TB_SKILL { get; set; }
        public virtual DbSet<TB_PREFIX> TB_PREFIX { get; set; }
        public virtual DbSet<TB_JOB_POSITION> TB_JOB_POSITION { get; set; }
        public virtual DbSet<TB_LOG_USER_ACTIVITY> TB_LOG_USER_ACTIVITY { get; set; }
        public virtual DbSet<TB_ACTION_CANDIDATE> TB_ACTION_CANDIDATE { get; set; }
        public virtual DbSet<TB_GENDER> TB_GENDER { get; set; }
        public virtual DbSet<TB_MARITALSTATUS> TB_MARITALSTATUS { get; set; }
        public virtual DbSet<TB_RELIGION> TB_RELIGION { get; set; }
        public virtual DbSet<TB_STATE_CANDIDATE> TB_STATE_CANDIDATE { get; set; }
        public virtual DbSet<TB_USER_ACCESS_MENU_CANDIDATE> TB_USER_ACCESS_MENU_CANDIDATE { get; set; }
        public virtual DbSet<TB_CANDIDATE_EDUCATION_HISTORY> TB_CANDIDATE_EDUCATION_HISTORY { get; set; }
        public virtual DbSet<TB_CITY> TB_CITY { get; set; }
        public virtual DbSet<TB_PROVINCE> TB_PROVINCE { get; set; }
        public virtual DbSet<TB_CANDIDATE_JOB_EXPERIENCE> TB_CANDIDATE_JOB_EXPERIENCE { get; set; }
        public virtual DbSet<TB_CANDIDATE_SELECTION_HISTORY> TB_CANDIDATE_SELECTION_HISTORY { get; set; }
        public virtual DbSet<TB_CANDIDATE> TB_CANDIDATE { get; set; }
        public virtual DbSet<TB_CANDIDATE_SKILL> TB_CANDIDATE_SKILL { get; set; }
        public virtual DbSet<TB_DELIVERY_HISTORY> TB_DELIVERY_HISTORY { get; set; }
        public virtual DbSet<TB_SKILL_JOB_EXPERIENCE> TB_SKILL_JOB_EXPERIENCE { get; set; }
        public virtual DbSet<TB_BENEFIT_JOB_EXPERIENCE> TB_BENEFIT_JOB_EXPERIENCE { get; set; }
    }
}
