//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BENEFIT_JOB_EXPERIENCE
    {
        public int ID { get; set; }
        public Nullable<int> JOB_EXP_ID { get; set; }
        public string BENEFIT { get; set; }
    }
}
