//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CANDIDATE_JOB_EXPERIENCE
    {
        public int ID { get; set; }
        public Nullable<int> CANDIDATE_ID { get; set; }
        public string INDUSTRIES { get; set; }
        public string CANDIDATE_POSITION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> CURRENT_SALARY { get; set; }
        public string SKILL_NAME { get; set; }
        public string JOBDESC { get; set; }
        public string BENEFIT { get; set; }
        public string COMPANY_NAME { get; set; }
        public string PROJCT { get; set; }
    
        public virtual TB_CANDIDATE TB_CANDIDATE { get; set; }
    }
}
