//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CANDIDATE_EDUCATION_HISTORY
    {
        public int ID { get; set; }
        public string CANDIDATE_SCHOOL_NAME { get; set; }
        public string CANDIDATE_SCHOOL_MAJOR { get; set; }
        public string CANDIDATE_SCHOOL_DEGREE { get; set; }
        public Nullable<double> CANDIDATE_SCHOOL_GPA { get; set; }
    }
}
