//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CANDIDATE_SELECTION_HISTORY
    {
        public int ID { get; set; }
        public Nullable<int> CANDIDATE_ID { get; set; }
        public Nullable<int> PIC_ID { get; set; }
        public string CANDIDATE_APPLIED_POSITION { get; set; }
        public string CANDIDATE_SUITABLE_POSITION { get; set; }
        public string CANDIDATE_SOURCE { get; set; }
        public Nullable<int> CANDIDATE_STATE { get; set; }
        public Nullable<decimal> CANDIDATE_EXPECTED_SALARY { get; set; }
        public Nullable<System.DateTime> PROCESS_DATE { get; set; }
        public string NOTES { get; set; }
    
        public virtual TB_CANDIDATE TB_CANDIDATE { get; set; }
        public virtual TB_STATE_CANDIDATE TB_STATE_CANDIDATE { get; set; }
        public virtual TB_USER TB_USER { get; set; }
    }
}
