//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOG_USER_ACTIVITY
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public string Notes { get; set; }
        public System.DateTime Time { get; set; }
    }
}
