//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_ACCESS_MENU_CANDIDATE
    {
        public int ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<int> SUB_MENU_CANDIDATE_ID { get; set; }
        public Nullable<int> ACTION_CANDIDATE_ID { get; set; }
    
        public virtual TB_ACTION_CANDIDATE TB_ACTION_CANDIDATE { get; set; }
        public virtual TB_ROLE TB_ROLE { get; set; }
        public virtual TB_SUBMENU TB_SUBMENU { get; set; }
    }
}
